Repository deltachat/deltachat-ios, pull requests merged in 2024-10, with the labels that each got.

#2319 Fix background notifications
  deltachat-ios/Helper/NotificationManager.swift
Labels: bug

#2343 Input field missing after adding a reaction
  deltachat-ios/Chat/ChatViewController.swift
Labels: bug

#2347 add 'select all' and 'mute' to chatlist
  deltachat-ios.xcodeproj/project.pbxproj
  deltachat-ios/Controller/ChatListViewController.swift
  deltachat-ios/Controller/ContactDetailViewController.swift
  deltachat-ios/Controller/GroupChatDetailViewController.swift
  deltachat-ios/Helper/MuteDialog.swift
  deltachat-ios/View/ChatListEditingBar.swift
  deltachat-ios/ViewModel/ChatListViewModel.swift
Labels: enhancement

#2341 fix multi-account notifications
  DcCore/DcCore/DC/events.swift
  deltachat-ios/Helper/NotificationManager.swift
Labels: bug, notify

#2351 tweak chatlist's swipe gestures
  deltachat-ios/Controller/ChatListViewController.swift
  deltachat-ios/Helper/MuteDialog.swift
  deltachat-ios/Helper/Utils.swift
Labels: enhancement
