Repository deltachat/deltachat-ios, pull requests merged in 2024-12, with the labels that each got.

#2447 remove email-address unconditionally from title
  CHANGELOG.md
  deltachat-ios/Chat/ChatViewController.swift
Labels: enhancement

#2444 fix warning: handle new authorization status 'limited'
  .github/workflows/ci.yml
  deltachat-ios/Controller/Settings/AdvancedViewController.swift
Labels: bug

#2465 Add two chats to placeholder-widget
  DcWidget/Assets.xcassets/AccentColor.colorset/Contents.json
  DcWidget/Assets.xcassets/broadcast.imageset/Contents.json
  DcWidget/Assets.xcassets/broadcast.imageset/icon-broadcast.png
  DcWidget/Assets.xcassets/saved-messages.imageset/Contents.json
  DcWidget/Assets.xcassets/saved-messages.imageset/icon-saved-messages.png
  DcWidget/WidgetProvider.swift
Labels: widget
