Repository deltachat/deltachat-ios, pull requests merged in 2024-11, with the labels that each got.

#2361 truncate too long text in generated images
  deltachat-ios/Helper/Utils.swift
Labels: bug

#2360 move webxdc-realtime out of experimental
  deltachat-ios/Chat/ChatViewController.swift
  deltachat-ios/Controller/Settings/AdvancedViewController.swift
  deltachat-ios/DC/DcContext.swift
Labels: enhancement

#2369 fix for safe area
  deltachat-ios/Chat/ChatViewController.swift
Labels: bug

#2368 dont ask for image access when opening gallery because it is not needed
  deltachat-ios/Helper/MediaPicker.swift
Labels: bug

#2367 webxdc vc memory leak fix
  deltachat-ios/Controller/WebxdcViewController.swift
Labels: bug, webxdc

#2374 disable two-finger pan gesture during search
  deltachat-ios/Controller/ChatListViewController.swift
Labels: bug

#2375 disable two-finger pan gesture during message search, fix 'more'
  deltachat-ios/Chat/ChatViewController.swift
Labels: bug

#2397 fix proxies added doubles sometimes
  deltachat-ios/Controller/Settings/Proxy/ProxySettingsViewController.swift
Labels: bug

#2398 tweak proxy icons
  deltachat-ios/Controller/ChatListViewController.swift
Labels: enhancement

#2393 when NSE is fetching, do not delay app start
  CHANGELOG.md
  DcCore/DcCore/Helper/DcUtils.swift
  deltachat-ios/AppDelegate.swift
  deltachat-ios/DC/DcAccount.swift
Labels: bug, notify

#2412 add new webxdc APIs
  DcCore/DcCore/DC/events.swift
  DcNotificationService/NotificationService.swift
  deltachat-ios/Chat/ChatViewController.swift
  deltachat-ios/Controller/WebxdcViewController.swift
  deltachat-ios/DC/DcMsg+Extension.swift
  deltachat-ios/DC/DcMsg.swift
  deltachat-ios/Helper/NotificationManager.swift
Labels: webxdc, wait-for-core
