Repository deltachat/deltachat-ios, pull requests merged in 2025-01, with the labels that each got.

#2477 Fix no notification and 30 sec stale app when NSE crashed in background from running out of memory
  DcCore/DcCore/Extensions/UserDefaults+Extensions.swift
  DcNotificationService/NotificationService.swift
  deltachat-ios/DC/DcAccount.swift
Labels: bug, notify

#2481 Reduced motion on chat messages
  deltachat-ios/Chat/ChatViewController.swift
Labels: enhancement

#2480 Prevent automatic limited access alert
  deltachat-ios/Info.plist
Labels: enhancement

#2392 Returns first responder after UIImagePickerController search bar selection on iOS 16
  deltachat-ios/Helper/GiveBackMyFirstResponder.swift
Labels: bug

#2489 do not write deprecated DC_CERTCK_ACCEPT_INVALID_CERTIFICATES
  deltachat-ios/Controller/AccountSetup/CertificateCheckController.swift
  deltachat-ios/DC/DcContext.swift
Labels: bug

#2506 force a name on editing profile
  deltachat-ios/Controller/Settings/SelfProfileViewController.swift
Labels: bug

#2521 show context menu on long-tapping proxies
  CHANGELOG.md
  deltachat-ios/Controller/Settings/Proxy/ProxySettingsViewController.swift
Labels: enhancement

#2511 set "tags" on profiles, mute and sort profiles
  CHANGELOG.md
  deltachat-ios/Chat/ChatViewController.swift
  deltachat-ios/Controller/AccountSwitchViewController.swift
  deltachat-ios/DC/DcAccount.swift
Labels: enhancement
